feat(action): use node for nix develop env export

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -157,4 +157,9 @@ runs:
       shell: bash
       env:
         NIX_DEVELOP_TARGET: ".#devShells.${{ steps.nix.outputs.system }}.${{ inputs.shell }}"
-      run: '"${{ github.action_path }}/nix-develop.sh" "$NIX_DEVELOP_TARGET"'
+      run: |
+        if ! command -v node >/dev/null; then
+          echo "::error::Node.js is required to load a development shell"
+          exit 1
+        fi
+        node "${{ github.action_path }}/nix-develop.mjs" "$NIX_DEVELOP_TARGET"
